### ISSUE TITLE
RES in white

### ISSUE THREAD

**Issue by Lonerider2010** [nederhof/resjs#4]
Thanks for this really useful environment.
Now I would like to set the documents to dark mode. Whereas I can manage to set the texts in <span> to white, I don't know how to set the symbols in <canvas> to white.
Can you please help me there?

**Comment by rillian** [comment]
Maybe something like
```css
canvas.res {
  filter: invert(1):
}
```
